=== elenaac949/gamesRus/archivos/XML/juegos.dtd
<!ELEMENT juegos (juego)*>
<!ELEMENT juego (titulo, desarrollador, distribuidor, año, relacionados, portada, ruta, sistemas, generos)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT desarrollador (#PCDATA)>
<!ELEMENT distribuidor (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT relacionados (relacionado)*>
<!ELEMENT relacionado (#PCDATA)>
<!ELEMENT portada (#PCDATA)>
<!ELEMENT ruta (#PCDATA)>
<!ELEMENT sistemas (sistema)+>
<!ELEMENT sistema (#PCDATA)>
<!ELEMENT generos (genero)+>
<!ELEMENT genero (#PCDATA)>

=== elenaac949/gamesRus/archivos/XML/juegos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE juegos SYSTEM "juegos.dtd">
<juegos>
  <juego>
    <titulo>Lemmings</titulo>
    <desarrollador>DMA Design Limited</desarrollador>
    <distribuidor>Psygnosis Limited</distribuidor>
    <año>1991</año>
    <relacionados>
      <relacionado>Oh No! More Lemmings</relacionado>
      <relacionado>Lemmings 2: The Tribes</relacionado>
    </relacionados>
    <portada>lemmings.jpg</portada>
    <ruta>lemmings.zip</ruta>
    <sistemas>
      <sistema>DOS</sistema>
    </sistemas>
    <generos>
      <genero>action</genero>
      <genero>puzzle</genero>
    </generos>
  </juego>
  <juego>
    <titulo>Oh No! More Lemmings</titulo>
    <desarrollador>DMA Design Limited</desarrollador>
    <distribuidor>Psygnosis Limited</distribuidor>
    <año>1991</año>
    <relacionados>
      <relacionado>Lemmings</relacionado>
      <relacionado>Lemmings 2: The Tribes</relacionado>
    </relacionados>
    <portada>oh_no_more_lemmings.jpg</portada>
    <ruta>oh_no_more_lemmings.jpg</ruta>
    <sistemas>
      <sistema>DOS</sistema>
    </sistemas>
    <generos>
      <genero>add-on</genero>
      <genero>puzzle</genero>
    </generos>
  </juego>
    <juego>
    <titulo>Lemmings 2: The Tribes</titulo>
    <desarrollador>DMA Design Limited</desarrollador>
    <distribuidor>Psygnosis Limited</distribuidor>
    <año>1993</año>
    <relacionados>
      <relacionado>Lemmings</relacionado>
      <relacionado>Oh No! More Lemmings</relacionado>
    </relacionados>
    <portada>lemmings_2_the_tribes.jpg</portada>
    <ruta>lemmings_2_the_tribes.zip</ruta>
    <sistemas>
      <sistema>DOS</sistema>
    </sistemas>
    <generos>
      <genero>puzzle</genero>
    </generos>
  </juego>
</juegos>
